name: Build Haxe Solar Files

on:
  push:
    branches: ['haxe']
  pull_request:
    branches: ['haxe']
  workflow_dispatch:

jobs:
    build:
      name: ${{matrix.os-name}} Build
      runs-on: ${{matrix.os}}
      strategy:
          fail-fast: false
          matrix:
            include:
              - os: ubuntu-latest
                os-name: Linux
                target: x86_64-unknown-linux-gnu
              - os: windows-latest
                os-name: Windows
                target: x86_64-pc-windows-msvc
              - os: macos-latest
                os-name: macOS-Intel
                target: x86_64-apple-darwin
              - os: macos-latest
                os-name: macOS-Arm64
                target: aarch64-apple-darwin

        steps:
            - uses: actions/checkout@v4
            - uses: krdlab/setup-haxe@v2
              with:
                haxe-version: 4.3.7
            
            - name: Install Libraries
              run: |
                haxelib install lime
                haxelib install openfl
                haxelib --never install flixel
                haxelib run lime setup flixel
                haxelib run lime setup
                haxelib install flixel-tools
                haxelib install flixel-ui
                haxelib install flixel-addons
                haxelib install haxeui-core
                haxelib install haxeui-flixel
              shell: cmd

            - name: Create Version Tag
              run: echo "${{github.run_id}}" > VERSION

            - name: Compile
              run: haxelib run lime build ${{matrix.target}} --app-version="4.0.0-${{ github.run_id}}"

            - name: Publish Artifact
              uses: actions/upload-artifact@v4
              with:
                name: Solar Submit ${{matrix.os-name}}
                path: export/${{matrix.target}}/

